spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:

jwt:
  secret-key: ${JWT}
  access-ttl: 1800
  refresh-ttl: 604800

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      probes:
        enabled: true
      group:
        startup:
          include: livenessState
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db

sentry:
  dsn: https://549949467178bc6b21e2ed5fe6fab367@o4511866903658496.ingest.us.sentry.io/4511866969784320
  # Add data like request headers and IP for users,
  # see https://docs.sentry.io/platforms/java/guides/spring-boot/data-management/data-collected/ for more info
  send-default-pii: true
  # Enable sending logs to Sentry
  logs:
    enabled: true
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for tracing.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  # Set profile-session-sample-rate to 1.0 to profile 100% of profile sessions.
  profile-session-sample-rate: 1.0
  # Set profile-lifecycle to trace to automatically start and stop
  # profiling when a transaction starts and finishes.
  profile-lifecycle: TRACE
